name: build

on:
  pull_request:
  push:
    branches:
      # avoid duplicate builds of PRs
      - main
      - test/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: install tex
        run: |
          sudo apt-get update && sudo apt-get -y install \
            ca-certificates \
            make \
            latexmk \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-bibtex-extra \
            texlive-xetex \
            biber \
            pdftk \
            git \
            python3

      - name: build draft
        run: |
            make draft
            test -f draft.pdf

      - uses: actions/upload-artifact@v2
        with:
          name: draft.pdf
          path: "draft.pdf"
          if-no-files-found: error

      - name: build final
        run: |
            make final
            test -f final.pdf

      - uses: actions/upload-artifact@v2
        with:
          name: final.pdf
          path: final.pdf
          if-no-files-found: error

      - name: page length check final.pdf
        run: |
            # display number of pages for debugging
            pdftk draft.pdf dump_data_annots output  | grep NumberOfPages
            # trigger error if too long
            make check-length-final



      # Comment out for now as the check script is not working yet
      # - name: check person-month data
      #   run: |
      #     make check
